development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mine_development
  pool: 5
  username: webapp
  password: webapp
  socket: /tmp/mysql.sock
  encoding: utf8

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mine_test
  pool: 5
  username: webapp
  password: webapp
  socket: /tmp/mysql.sock
  encoding: utf8

production:
  development

cucumber:
  <<: *test